### ISSUE TITLE
Customer Satisfaction (CSAT) survey interrupts ongoing conversations 

### ISSUE THREAD

**Issue by rubycalling** [fbsamples/original-coast-clothing#18]
#### Describe the bug
After a person talks to an agent for order, billing or other issues, we send a CSAT survey after ~1 minute. But this survey often interrupt any further conversation with the experience. Also if a person talks to an agent after another, we send 2x the CSAT which add a lot of noise in the conversation.

#### To Reproduce
1. Send 'help'
2. Click on 'Order Inquiries'
3. Click on 'Outfit suggestions' in the persistent menu
4. Wait until you receive the CSAT survey (~1 min)
5. Observe that the quick replies sent with '_Are you looking for an outfit for yourself or someone else?_' are replaced with the quick replies from the CSAT survey

#### Expected behavior
The survey should be sent when no _recent_ interaction has occurred between the user and the experience, to avoid interrupting the conversation flow. Also we should flag when a survey has been sent in the past ~24h to avoid repeated CSAT messages.

#### Screenshots
![IMG_903AE94F7B1C-1](https://user-images.githubusercontent.com/15194296/58964648-27e33280-87a7-11e9-8e11-64bf6ee9ecc0.jpeg)

#### Possible Solution
- Send the CSAT survey right after the interaction with a live agent to avoid interrupting the conversation after further messages
- Add a label `this.survey = "timestamp"` in https://github.com/fbsamples/original-coast-clothing/blob/master/services/user.js to check if last survey > 24h before sending a new one

**Comment by jorgeluiso** [comment]
Another potential solution
Add a flag to the user var, indicating: CSAT pending for persona X. 
After the sleep is done, review if the flag is present before replying with the survey.

If the user engages with a new flow, clear the flag. The context is lost due to the new flow.
