### ISSUE TITLE
Error when running the code on AWS EC2.

### ISSUE THREAD

**Issue by rdspencer** [fbsamples/original-coast-clothing#35]
When attempting to run the example (on an AWS EC2) I get:
/var/www/html/bot1/..bot2/original-coast-clothing/app.js:15
  { urlencoded, json } = require("body-parser"),
  ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by jorgeluiso** [comment]
We have tested only in Heroku. So not sure how to solve this issue. If you find the solution that will make it run on EC2 and is compatible with running the code locally create a pull request so we can merge it

**Comment by virtuallyawake** [comment]
@rdspencer Could it be that you are running an old version of nodejs? Looks like an issue with destructuring the return value from the require() into { urlencoded, json }. 
Could you make sure you are running v10 or higher?

**Comment by jorgeluiso** [comment]
Closing because this is old.
