### ISSUE TITLE
I having issues with getting user profile (typeError: finally not found)

### ISSUE THREAD

**Issue by viveksachidananda** [fbsamples/original-coast-clothing#43]
Hello,

I did the setup as per the video and then when I send message to my page, the backend receives the message but it fails with an exception:
GraphAPI.getUserProfile() ... finally not found.

Can you help me?
<img width="818" alt="Screenshot 2019-10-02 at 09 16 30" src="https://user-images.githubusercontent.com/10163902/66039950-88e10400-e516-11e9-930d-7e3b36824336.png">

**Comment by jorgeluiso** [comment]
Check that you have node installed and have ran yarn install.

For a detailed step by step you can follow this guide, it should help identify the issue.
https://developers.facebook.com/docs/messenger-platform/getting-started/sample-apps/original-coast-clothing#local_install
