### ISSUE TITLE
Improve variables consistency and messenger entrypoint comment in Receive.

### ISSUE THREAD

**Issue by aug2uag** [fbsamples/original-coast-clothing#55]
In services/receive.js, the `handleTextMessage` function handles the messenger input with a default handler. The variables of this function are not declared, and also in the default handler the `message` variable is unused.

The consistency of the variables should be defined with an `event` variable as `handleMessage` does. It would also benefit to have a comment to know where the default handler is for the messenger event.

**Comment by Barbog** [comment]
Thanks for the suggestions, aug2uag. We've added those suggestions to the code.
