### ISSUE TITLE
Localtunnel error

### ISSUE THREAD

**Issue by sompetch0249** [fbsamples/original-coast-clothing#57]
Hi there,

Under Using Local Tunnel to get incoming messages, there is a Localtunnel link that would link me to an external https address. But after I clicked on it returned me this message, "You Can't Go to This Link From Facebook. The link you tried to visit goes against our Community Standards."

I was not sure how to fix this issue, please let me know if anyone knows the solution. 

Thank you so much in advance,
Pack

**Comment by jorgeluiso** [comment]
LocalTunnel and Ngrok are developers tools designed to create a tunnel into your dev computer. Not mean for production use. Alternatively you can deploy the code into Heroku to test how it works and develop. To use Ngrok substitute the LocalTunnel instructions for these ones.

npm install ngrok -g
ngrok http 3000

**Comment by tanvan81** [comment]
But when I run on http, port 4000, show error
First, I've config

APP_URL=http://localhost:4000

when run on code on local, 

**WARNING: Your APP_URL does not begin with "https://"**

And run url : [(http://localhost:4000/profile?mode=all&verify_token=xxxx)]

ERROR - Need a proper API_URL in the .env file

**Comment by wanderingstan** [comment]
@sompetch0249 , this issue should be fixed by #74 — Please try again using ngrok, glitch, heroku, or some other hosting solution.
