### ISSUE TITLE
Can't find the place where the Get Started is created 

### ISSUE THREAD

**Issue by daGonen** [fbsamples/original-coast-clothing#59]
Hello there,
I can't find the place where you are actually creating the Get Started button, nor the Greeting function, and not how you generate those 3 messages after the Get Started button is pressed.
I did find where you store those messages, in the Locales\en_US.json file, and then generated in the i18 file, but i couldn't find whats triggered it in your app. I hoped you'll be able to help me,
Thanks!

**Comment by jorgeluiso** [comment]
Is done when setting the profile
https://github.com/fbsamples/original-coast-clothing/blob/master/app.js#L165
