### ISSUE TITLE
commentgity _id should be comment_id

### ISSUE THREAD

**Issue by mrharel** [fbsamples/original-coast-clothing#61]
https://github.com/fbsamples/original-coast-clothing/blob/adebfb4cb799200c5a0d7109885a030c79e87154/app.js#L94

It seems like a typo: "commentgity _id" should be "comment_id"

**Comment by Riandy** [comment]
Thanks for the catch!

Fixed in https://github.com/fbsamples/original-coast-clothing/pull/62

Regards
Riandy

**Comment by rubycalling** [comment]
Closing the issue as this has been fixed in #62.
