### ISSUE TITLE
save whole conversation 

### ISSUE THREAD

**Issue by WilliamsToTo** [fbsamples/original-coast-clothing#64]
In our bot, we mainly use human agents to talk with audiences. Is there any way to store the whole conversation between audiences and human agents. In the source code, I find the place to get audience's responses, but I don't know how to get the utterances from human agents.

**Comment by Barbog** [comment]
This sounds more like a design question than anything. When talking about using human agents, I would expect the human agents to be using an interface with a code-base similar to the bot. That is, a bot through which the human agent would type the message and which would accept the webhooks regarding that conversation. 

In such a situation, you could be saving the conversation text on message send and webhook receipt.  The equivalent location in this project would be the `/services/receive.js` file, with logging of received messages in one of the `handleXYZ` functions and some added code to have the human agent send their own responses (with logging occurring  there as well).
