### ISSUE TITLE
Includes content have reported as abusive

### ISSUE THREAD

**Issue by felangga** [fbsamples/original-coast-clothing#67]
I'm running this sample and it's show this error

`Request sent: {
  error: {
    message: "Your message couldn't be sent because it includes content that other people on Facebook have reported as abusive.",
    type: 'OAuthException',
    code: 368,
    error_data: {
      sentry_block_data: 'Aei4oUoPdnkY3kHXoCgrD8__g_sqxljbQdf5FowqWRVAHgZBJ-c5Rf5HawmgnfWLVMcd-Gk5neXILmQHGft4lNjEdB5ak-jCU-2em8u8ghBMS48VDr-zI0SkNs7BrXdqH4LrjdceV2jbOXawarlyOxSloh_nJQQvoTogFWCRBq1KicrZ4raWV2o4_mVKfa6hm7dansbZn12UFilsLwOnn4PCZNZUJxYp-WRLeT-9hWHvH7hWfvuDZV-eUZyYQs3cDFxbpoTyMl3ojCYDY7B0NwFA8qsOraiAwm27IBOhuSuKsAQae2u4fNfGin0ES8lBXGLf7pcZz0PtKXXcnA570oq-Yf0Oq9gPBZSfhtqjtPGeiA',
      help_center_id: 0
    },
    error_subcode: 1346003,
    error_user_msg: '',
    fbtrace_id: 'AzRnhzCIoElDzFIzNhIV9_L'
  }
}
`

How to resolve this issue ?

**Comment by NietoCurcio** [comment]
Same here, I could test the messenger api making the deploy to heroku, and in the webhook app facebook configuration, a setted up the url provided by heroku, that works for me. I don't why when we set the url using the local tunnel as in the documentations I get that problem in the request and cannot set the url in the app facebook configuration.

**Comment by jorgeluiso** [comment]
This looks like an enforcement action not related to the demo code. The app is expected to handle the error, in this case review the experience that led to its flagging.

**Comment by NickSutton** [comment]
Also receiving the above error. Did anyone work out how to address it?
