### ISSUE TITLE
RGPD problems (Europe) : impossible to solve ?

### ISSUE THREAD

**Issue by Emilien-Valain** [fbsamples/original-coast-clothing#78]
With the new laws in Europe it seems the chatbot doesn't work anymore there. 

When running the app after following the tutorial for the local environement 
[https://developers.facebook.com/docs/messenger-platform/getting-started/sample-experience](url)
I got  this : 

Request sent: {"error":{"message":"(#10) Cette action n\u2019a pas \u00e9t\u00e9 envoy\u00e9e en raison de nouvelles r\u00e8gles de confidentialit\u00e9 en Europe. Voir la documentation d\u00e9veloppeur pour plus d\u2019informations.","type":"OAuthException","code":10,"error_subcode":2018336,"fbtrace_id":"ATwZHxxCrzYl--VAz7l3vp4"}}
Creation failed: Error: 400
 
Is it impossible now for Europeans to create Messenger bots ?

**Comment by wanderingstan** [comment]
Hi Emilien, it should be possible in Europe. Can you pinpoint exactly what step you were on, or what state the app was in, when you encountered that error? Also, were you following the instructions on the [docs](https://developers.facebook.com/docs/messenger-platform/getting-started/sample-experience) or from the repo readme? I believe the readme is more up to date. Thanks!

**Comment by NickSutton** [comment]
I get the same here in UK.

After setting `profile?mode=all&verify_token=xxx` etc I get a bundle of text back, which looks ok until 
````
request sent: {"error":
  {"message":"Your message couldn't be sent because it includes content that other people on Facebook have reported as abusive.","type":"OAuthException","code":368,"error_data":    {"sentry_block_data":"<long string of data ", "help_center_id":0,"is_silent":false},
"error_subcode":1346003,"error_user_msg":"","fbtrace_id":"more values here"}}
````

and then

````
Request sent: {"error":
  {"message":"(#10) This action was not submitted due to new privacy rules in Europe. See developer documentation for more info.",
  "type":"OAuthException","code":10,"error_subcode":2018336,"fbtrace_id":"<values>"}}
Creation failed: Error: 400
````

**Comment by wanderingstan** [comment]
@NickSutton @Emilien-Valain it looks like this is a red herring: 

Ah, I suspect you're trying to use localtunnel for port forwarding, this is causing an error (known issue), and then the _reporting_ of this error is being bloacked by European privacy laws. 

I see our internal docs still reference localtunnel. I will get that fixed. In the mean time, try following the instructions in the [README.md](https://github.com/fbsamples/original-coast-clothing/blob/master/README.md) or use an alternate method of setting up your server.

**Comment by wanderingstan** [comment]
I'm going to close this out assuming this readme fix resolved the issue—let me know and/or re-open this issue f you see this issue again going forward.
