### ISSUE TITLE
webhook setting

### ISSUE THREAD

**Issue by DianeX** [fbsamples/original-coast-clothing#8]
Hello Developpers! i have some difficulty in adding the callback url in webhook.
Can you help me please what to write there i have tried with https://curvy-firefox-32.localtunnel.me/ but it can't. Thanks

**Comment by rubycalling** [comment]
Hey @DianeX, have you followed all the steps mentioned in the documentation?https://developers.facebook.com/docs/messenger-platform/getting-started/sample-apps/original-coast-clothing#local_configure

**Comment by DianeX** [comment]
Yes, It is what I followed. And It is on the "Configure your Facebook app webhook subscription and set the Messenger profile"-things that I've stack. In fact, I need some example of the url which should be in the "Callback Url" in webhook to "Subscribe to events". [case of localtunnel]

**Comment by rubycalling** [comment]
Once you have created a `.env` file using the [.sample.env](https://github.com/fbsamples/original-coast-clothing/blob/master/.sample.env) provided with the project and then restarted your server, your should be able to run `http://localhost:3000/profile?mode=all&verify_token=<VERIFY_TOKEN>`. Then, the setup of the webhook url and the subscription to the events will be automatically done for you!

**Comment by DianeX** [comment]
Thank you @rubycalling I fixed it :D I should run "node app.js" first before "lt --port 3000". Thank you very much

**Comment by rubycalling** [comment]
![image](https://media0.giphy.com/media/tCV2LrPPYfqCY/giphy.gif?cid=790b76115cf530df4368335463a1ca5d&rid=giphy.gif)
