### ISSUE TITLE
No Greetings Messages with buttons and products are not being displayed

### ISSUE THREAD

**Issue by sohaibtechno123** [fbsamples/original-coast-clothing#83]
Hi, 
I followed all the steps to clone your git project and then deployed it to my heroku app without any error. Bot is not working as it should be like you showed in video, may be I did something wrong IDK. Here's  my link to FB page I attached my bot to

Here's video recording of my issue
https://youtu.be/Fcc6sbMIE_0

**Comment by Barbog** [comment]
Given you got the initial webhook but that it stops responding, it looks like it may be related to a small bug which is being corrected shortly.  

In the meantime, check to ensure that there is *no* semicolon  on line 100 of /services/receive.js
`       message: event.message.text;`

**Comment by wanderingstan** [comment]
Fixed with c3fa0eb12c01740bf0e97844dc4bb46de5fff137
