### ISSUE TITLE
Unable to callSubscriptionsAPI

### ISSUE THREAD

**Issue by ebernardinojr** [fbsamples/original-coast-clothing#84]
#### Describe the bug
I followed the step by step procedure and was successful up to node app.js. however once I sent a message the bot is not replying and in my terminal it says 

Unable to callSubscriptionsAPI: Bad Request {
  error: {
    message: '(#2200) Callback verification failed with the following errors: HTTP Status Code = 404; HTTP Message = Not Found',
    type: 'OAuthException',
    code: 2200,
    fbtrace_id: 'AbYveT9_aL1Xm1ckgbobFCY'
  }

<img width="965" alt="Screen Shot 2021-06-28 at 9 25 33 AM" src="https://user-images.githubusercontent.com/86404464/123566716-f2c53500-d7f2-11eb-8abb-e281c4efdf8f.png">

**Comment by Barbog** [comment]
Hi ebernardinojr. It sounds like your app may not be fully configured in Heroku. Perhaps the URL has a typo, or the Heroku configs aren't fully set up. 
Please consider the solutions presented in [this related post](https://github.com/jw84/messenger-bot-tutorial/issues/15). Furthermore, ensure that your verification token does not include any special characters (as they may not always be correctly escaped).

**Comment by ebernardinojr** [comment]
> Hi ebernardinojr. It sounds like your app may not be fully configured in Heroku. Perhaps the URL has a typo, or the Heroku configs aren't fully set up.
> Please consider the solutions presented in [this related post](https://github.com/jw84/messenger-bot-tutorial/issues/15). Furthermore, ensure that your verification token does not include any special characters (as they may not always be correctly escaped).

HI @Barbog, good day thank you for your reply. I was able to successfully setup the heroku https://arcane-stream-73934.herokuapp.com/profile?mode=all&verify_token=my_first_bot. Webhook was also successfully setup, kindly see image

However my bot is still not replying. did i missed something in the setup?

<img width="924" alt="Screen Shot 2021-06-29 at 12 02 04 PM" src="https://user-images.githubusercontent.com/86404464/123735725-4eb2bb00-d8d2-11eb-834b-a00c8883ec5c.png">
