### ISSUE TITLE
How does OriginalCoastClothing avoid the "User wants to send you a message" speed bump?

### ISSUE THREAD

**Issue by bobber205** [fbsamples/original-coast-clothing#86]
When I use this codebase to prototype a interact-able experience for my test_  prefixed IG account I see the Ice Breakers and once pressed and a message is sent -- I get a "User wants to send you a message" request notification.

I approve the notification and there are no further webhook events and I have to resend my message after the request has been approved.

Same account sends a first time message to OriginalCoastClothing hitting an Icebreaker button and gets a response.

What's up?

**Comment by Barbog** [comment]
Thanks for letting us know, bobber205. 
This may be a misconfiguration or something going awry. 

Kindly file a bug about this so that it can be properly triaged so that we can get more eyes on the issue:
https://developers.facebook.com/support/bugs/

**Comment by Barbog** [comment]
Please be aware that this does not seem to be an issue with the OriginalCoastClothing sample bot.
And thank you again for filing it. 👍
