### ISSUE TITLE
App Type needs to be "Business"

### ISSUE THREAD

**Issue by rdai** [fbsamples/original-coast-clothing#91]
The guide says "Facebook App: Contains the settings for your app, including access tokens. To create a new app, visit https://developers.facebook.com/ and click on Add New App"

It should specify when given the choice, you must select "Business" as the app type or there won't be the option to add Messenger as a product.

**Comment by Barbog** [comment]
Hi rdai,
It does depend on the type of app you create, but the two are 'Instant Games' and 'Business'.

EG: I just clicked through from that link, selected 'CreateApp' from the "My Apps" dropdown, and selected _Instant Game_ as my type, and Messenger was available.
![image](https://user-images.githubusercontent.com/129722/135136070-ce77c271-0e02-4479-9bdf-07d368eae6aa.png)

But note that this is only for the Audience category selection of "Manage integrations for your business". The other categories will provide other options (but require Business Verification).

Thank you for pointing this out.
